title:            Mikael Hallendal
disqus_shortname: mhallendal
search:           false

markdown: redcarpet
pygments: true

permalink: /blog/:title

owner:
    name:    Mikael Hallendal
    email:   hallski@hallski.org
    twitter: mhallendal
    github:  mhallendal

links:
    - title: Index
      url: /
    - title: About
      url: /about
    - title: Posts
      url: /posts
