title: Hallski.org

highlighter: rouge

permalink: /blog/:title

disqus_shortname: hallski
owner:
    name:     Mikael Hallendal
    email:    hallski@hallski.org
    twitter:  mhallendal
    github:   mhallendal
    linkedin: mhallendal
