name: GitHub Pages

on:
  push:
    branches:
      - svelte

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2
        with:
          version: '6.19.1'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
